Update pyproject.toml
The new version of `setuptools` removed the `pkg_resources` package, causing `uv sync` to fail with an error:

> https://setuptools.pypa.io/en/latest/history.html#v82-0-0

```
❯ uv sync
Using CPython 3.10.12 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
  × Failed to build `openai-whisper==20240930`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/root/.cache/uv/builds-v0/.tmpvZanSd/lib/python3.10/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/root/.cache/uv/builds-v0/.tmpvZanSd/lib/python3.10/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/root/.cache/uv/builds-v0/.tmpvZanSd/lib/python3.10/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/root/.cache/uv/builds-v0/.tmpvZanSd/lib/python3.10/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
      ModuleNotFoundError: No module named 'pkg_resources'

      hint: This error likely indicates that `openai-whisper@20240930` depends on `pkg_resources`, but doesn't declare it as a build dependency. If `openai-whisper` is a
      first-party package, consider adding `pkg_resources` to its `build-system.requires`. Otherwise, either add it to your `pyproject.toml` under:

      [tool.uv.extra-build-dependencies]
      openai-whisper = ["pkg_resources"]

      or `uv pip install pkg_resources` into the environment and re-run with `--no-build-isolation`.
  help: `openai-whisper` (v20240930) was included because `gpustack[all]` (v0.0.0) depends on `vox-box==0.0.19` (v0.0.19) which depends on `openai-whisper>=20240930, <20240931`
```